//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMICApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalization
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public int HospitalizationReferralId { get; set; }
        public Nullable<bool> RefusalByPatient { get; set; }
        public Nullable<bool> Cancellation { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<int> HospitalBedId { get; set; }
    
        public virtual HospitalBed HospitalBed { get; set; }
        public virtual HospitalizationReferral HospitalizationReferral { get; set; }
    }
}
