//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMICApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalizationReferral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalizationReferral()
        {
            this.Hospitalizations = new HashSet<Hospitalization>();
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string Diagnosis { get; set; }
        public string Purpose { get; set; }
        public int DepartmentId { get; set; }
        public bool Conditions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalization> Hospitalizations { get; set; }
        public virtual HospitalizationDepartment HospitalizationDepartment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
