//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMICApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROF2024Entities : DbContext
    {
        public PROF2024Entities()
            : base("name=PROF2024Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeseaseHistory> DeseaseHistories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<HospitalBed> HospitalBeds { get; set; }
        public virtual DbSet<Hospitalization> Hospitalizations { get; set; }
        public virtual DbSet<HospitalizationDepartment> HospitalizationDepartments { get; set; }
        public virtual DbSet<HospitalizationReferral> HospitalizationReferrals { get; set; }
        public virtual DbSet<Medcard> Medcards { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TreatmentEvent> TreatmentEvents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
