//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMICApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentEvent
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int DoctorId { get; set; }
        public int EventTypeId { get; set; }
        public string Title { get; set; }
        public string Results { get; set; }
        public string Recommendations { get; set; }
        public int PatientId { get; set; }
        public int Price { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
