//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeseaseHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeseaseHistory()
        {
            this.Prescriptions = new HashSet<Prescription>();
            this.Referrals = new HashSet<Referral>();
        }
    
        public int Id { get; set; }
        public System.DateTime VisitDate { get; set; }
        public int MedcardId { get; set; }
        public string Description { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Medcard Medcard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referral> Referrals { get; set; }
    }
}
