//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientReception
    {
        public int Id { get; set; }
        public System.TimeSpan TimeBegin { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
        public Nullable<int> PatientId { get; set; }
        public bool Status { get; set; }
        public int TimeSheetId { get; set; }
        public int CouponNumber { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual TimeSheet TimeSheet { get; set; }
    }
}
