//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedInfoSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medcard()
        {
            this.DeseaseHistories = new HashSet<DeseaseHistory>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Diagnosis { get; set; }
        public System.DateTime LastVisitDate { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public string QR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeseaseHistory> DeseaseHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
