//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedInfoSystemApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int Id { get; set; }
        public int EventTypeId { get; set; }
        public int DeseaseHistoryId { get; set; }
    
        public virtual DeseaseHistory DeseaseHistory { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
